apiVersion: v2
appVersion: v1.11.25
description: Communicate the way you want with Riot - a universal secure chat app entirely under your control.
icon: https://raw.githubusercontent.com/vector-im/element-web/develop/res/themes/element/img/logos/element-logo.svg
name: element-web
version: 1.3.0
type: application
keywords:
  - synapse
  - chat
  - matrix
  - riot
  - element
home: https://element.io/
sources:
  - https://github.com/vector-im/element-web
maintainers:
  - name: Gavin Mogan
    email: helm@gavinmogan.com
annotations:
  artifacthub.io/changes: |2
     - "thing ([3e05d16](https://github.com/halkeye/test-semantic-release-helm3/commit/3e05d16809b4a8b925929019756c49cf17b6acdb))"
     - "this is a feat ([fecf8c3](https://github.com/halkeye/test-semantic-release-helm3/commit/fecf8c312ee23f87ef09939ff7a546cc7e70641b))"
  artifacthub.io/containsSecurityUpdates: 'true'
  artifacthub.io/images: |
    - name: element-web
      image: "vectorim/element-web:v1.11.25"
