apiVersion: v2
appVersion: "v1.11.25" # image "vectorim/element-web"
description: Communicate the way you want with Riot - a universal secure chat app entirely under your control.
icon: https://raw.githubusercontent.com/vector-im/element-web/develop/res/themes/element/img/logos/element-logo.svg
name: element-web
version: 1.0.1
type: application
keywords:
  - synapse
  - chat
  - matrix
  - riot
  - element
home: https://element.io/
sources:
  - https://github.com/vector-im/element-web
maintainers:
  - name: Gavin Mogan
    email: helm@gavinmogan.com
annotations:
  artifacthub.io/changes:
    - '## [1.0.1](https://github.com/halkeye/test-semantic-release-helm3/compare/v1.0.0...v1.0.1) (2023-03-19)'
    - '### Bug Fixes'
    - '* trimmed changelogs ([91e6e44](https://github.com/halkeye/test-semantic-release-helm3/commit/91e6e443f58557adb9e8a3ac105b145fae2212c0))'
  artifacthub.io/containsSecurityUpdates: 'true'
  artifacthub.io/images: |
    - name: element-web
      image: "vectorim/element-web:v1.11.25"
